
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BotMessage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BotMessage
 * 
 */
export type BotMessageModel = runtime.Types.Result.DefaultSelection<Prisma.$BotMessagePayload>

export type AggregateBotMessage = {
  _count: BotMessageCountAggregateOutputType | null
  _min: BotMessageMinAggregateOutputType | null
  _max: BotMessageMaxAggregateOutputType | null
}

export type BotMessageMinAggregateOutputType = {
  id: string | null
  botId: string | null
  channelId: string | null
  guildId: string | null
  content: string | null
  externalMessageId: string | null
  status: $Enums.BotMessageStatus | null
  errorMessage: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BotMessageMaxAggregateOutputType = {
  id: string | null
  botId: string | null
  channelId: string | null
  guildId: string | null
  content: string | null
  externalMessageId: string | null
  status: $Enums.BotMessageStatus | null
  errorMessage: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BotMessageCountAggregateOutputType = {
  id: number
  botId: number
  channelId: number
  guildId: number
  content: number
  externalMessageId: number
  status: number
  errorMessage: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type BotMessageMinAggregateInputType = {
  id?: true
  botId?: true
  channelId?: true
  guildId?: true
  content?: true
  externalMessageId?: true
  status?: true
  errorMessage?: true
  createdAt?: true
  updatedAt?: true
}

export type BotMessageMaxAggregateInputType = {
  id?: true
  botId?: true
  channelId?: true
  guildId?: true
  content?: true
  externalMessageId?: true
  status?: true
  errorMessage?: true
  createdAt?: true
  updatedAt?: true
}

export type BotMessageCountAggregateInputType = {
  id?: true
  botId?: true
  channelId?: true
  guildId?: true
  content?: true
  externalMessageId?: true
  status?: true
  errorMessage?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type BotMessageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BotMessage to aggregate.
   */
  where?: Prisma.BotMessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BotMessages to fetch.
   */
  orderBy?: Prisma.BotMessageOrderByWithRelationInput | Prisma.BotMessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BotMessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BotMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BotMessages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BotMessages
  **/
  _count?: true | BotMessageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BotMessageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BotMessageMaxAggregateInputType
}

export type GetBotMessageAggregateType<T extends BotMessageAggregateArgs> = {
      [P in keyof T & keyof AggregateBotMessage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBotMessage[P]>
    : Prisma.GetScalarType<T[P], AggregateBotMessage[P]>
}




export type BotMessageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BotMessageWhereInput
  orderBy?: Prisma.BotMessageOrderByWithAggregationInput | Prisma.BotMessageOrderByWithAggregationInput[]
  by: Prisma.BotMessageScalarFieldEnum[] | Prisma.BotMessageScalarFieldEnum
  having?: Prisma.BotMessageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BotMessageCountAggregateInputType | true
  _min?: BotMessageMinAggregateInputType
  _max?: BotMessageMaxAggregateInputType
}

export type BotMessageGroupByOutputType = {
  id: string
  botId: string
  channelId: string
  guildId: string | null
  content: string
  externalMessageId: string
  status: $Enums.BotMessageStatus
  errorMessage: string | null
  createdAt: Date
  updatedAt: Date
  _count: BotMessageCountAggregateOutputType | null
  _min: BotMessageMinAggregateOutputType | null
  _max: BotMessageMaxAggregateOutputType | null
}

export type GetBotMessageGroupByPayload<T extends BotMessageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BotMessageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BotMessageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BotMessageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BotMessageGroupByOutputType[P]>
      }
    >
  >



export type BotMessageWhereInput = {
  AND?: Prisma.BotMessageWhereInput | Prisma.BotMessageWhereInput[]
  OR?: Prisma.BotMessageWhereInput[]
  NOT?: Prisma.BotMessageWhereInput | Prisma.BotMessageWhereInput[]
  id?: Prisma.StringFilter<"BotMessage"> | string
  botId?: Prisma.StringFilter<"BotMessage"> | string
  channelId?: Prisma.StringFilter<"BotMessage"> | string
  guildId?: Prisma.StringNullableFilter<"BotMessage"> | string | null
  content?: Prisma.StringFilter<"BotMessage"> | string
  externalMessageId?: Prisma.StringFilter<"BotMessage"> | string
  status?: Prisma.EnumBotMessageStatusFilter<"BotMessage"> | $Enums.BotMessageStatus
  errorMessage?: Prisma.StringNullableFilter<"BotMessage"> | string | null
  createdAt?: Prisma.DateTimeFilter<"BotMessage"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BotMessage"> | Date | string
  bot?: Prisma.XOR<Prisma.BotScalarRelationFilter, Prisma.BotWhereInput>
}

export type BotMessageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  botId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  guildId?: Prisma.SortOrderInput | Prisma.SortOrder
  content?: Prisma.SortOrder
  externalMessageId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  bot?: Prisma.BotOrderByWithRelationInput
}

export type BotMessageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BotMessageWhereInput | Prisma.BotMessageWhereInput[]
  OR?: Prisma.BotMessageWhereInput[]
  NOT?: Prisma.BotMessageWhereInput | Prisma.BotMessageWhereInput[]
  botId?: Prisma.StringFilter<"BotMessage"> | string
  channelId?: Prisma.StringFilter<"BotMessage"> | string
  guildId?: Prisma.StringNullableFilter<"BotMessage"> | string | null
  content?: Prisma.StringFilter<"BotMessage"> | string
  externalMessageId?: Prisma.StringFilter<"BotMessage"> | string
  status?: Prisma.EnumBotMessageStatusFilter<"BotMessage"> | $Enums.BotMessageStatus
  errorMessage?: Prisma.StringNullableFilter<"BotMessage"> | string | null
  createdAt?: Prisma.DateTimeFilter<"BotMessage"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BotMessage"> | Date | string
  bot?: Prisma.XOR<Prisma.BotScalarRelationFilter, Prisma.BotWhereInput>
}, "id">

export type BotMessageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  botId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  guildId?: Prisma.SortOrderInput | Prisma.SortOrder
  content?: Prisma.SortOrder
  externalMessageId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.BotMessageCountOrderByAggregateInput
  _max?: Prisma.BotMessageMaxOrderByAggregateInput
  _min?: Prisma.BotMessageMinOrderByAggregateInput
}

export type BotMessageScalarWhereWithAggregatesInput = {
  AND?: Prisma.BotMessageScalarWhereWithAggregatesInput | Prisma.BotMessageScalarWhereWithAggregatesInput[]
  OR?: Prisma.BotMessageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BotMessageScalarWhereWithAggregatesInput | Prisma.BotMessageScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BotMessage"> | string
  botId?: Prisma.StringWithAggregatesFilter<"BotMessage"> | string
  channelId?: Prisma.StringWithAggregatesFilter<"BotMessage"> | string
  guildId?: Prisma.StringNullableWithAggregatesFilter<"BotMessage"> | string | null
  content?: Prisma.StringWithAggregatesFilter<"BotMessage"> | string
  externalMessageId?: Prisma.StringWithAggregatesFilter<"BotMessage"> | string
  status?: Prisma.EnumBotMessageStatusWithAggregatesFilter<"BotMessage"> | $Enums.BotMessageStatus
  errorMessage?: Prisma.StringNullableWithAggregatesFilter<"BotMessage"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BotMessage"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"BotMessage"> | Date | string
}

export type BotMessageCreateInput = {
  id?: string
  channelId: string
  guildId?: string | null
  content: string
  externalMessageId: string
  status?: $Enums.BotMessageStatus
  errorMessage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  bot: Prisma.BotCreateNestedOneWithoutMessagesInput
}

export type BotMessageUncheckedCreateInput = {
  id?: string
  botId: string
  channelId: string
  guildId?: string | null
  content: string
  externalMessageId: string
  status?: $Enums.BotMessageStatus
  errorMessage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BotMessageUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.StringFieldUpdateOperationsInput | string
  externalMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBotMessageStatusFieldUpdateOperationsInput | $Enums.BotMessageStatus
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  bot?: Prisma.BotUpdateOneRequiredWithoutMessagesNestedInput
}

export type BotMessageUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  botId?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.StringFieldUpdateOperationsInput | string
  externalMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBotMessageStatusFieldUpdateOperationsInput | $Enums.BotMessageStatus
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BotMessageCreateManyInput = {
  id?: string
  botId: string
  channelId: string
  guildId?: string | null
  content: string
  externalMessageId: string
  status?: $Enums.BotMessageStatus
  errorMessage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BotMessageUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.StringFieldUpdateOperationsInput | string
  externalMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBotMessageStatusFieldUpdateOperationsInput | $Enums.BotMessageStatus
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BotMessageUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  botId?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.StringFieldUpdateOperationsInput | string
  externalMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBotMessageStatusFieldUpdateOperationsInput | $Enums.BotMessageStatus
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BotMessageListRelationFilter = {
  every?: Prisma.BotMessageWhereInput
  some?: Prisma.BotMessageWhereInput
  none?: Prisma.BotMessageWhereInput
}

export type BotMessageOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BotMessageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  botId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  externalMessageId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BotMessageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  botId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  externalMessageId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BotMessageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  botId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  externalMessageId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BotMessageCreateNestedManyWithoutBotInput = {
  create?: Prisma.XOR<Prisma.BotMessageCreateWithoutBotInput, Prisma.BotMessageUncheckedCreateWithoutBotInput> | Prisma.BotMessageCreateWithoutBotInput[] | Prisma.BotMessageUncheckedCreateWithoutBotInput[]
  connectOrCreate?: Prisma.BotMessageCreateOrConnectWithoutBotInput | Prisma.BotMessageCreateOrConnectWithoutBotInput[]
  createMany?: Prisma.BotMessageCreateManyBotInputEnvelope
  connect?: Prisma.BotMessageWhereUniqueInput | Prisma.BotMessageWhereUniqueInput[]
}

export type BotMessageUncheckedCreateNestedManyWithoutBotInput = {
  create?: Prisma.XOR<Prisma.BotMessageCreateWithoutBotInput, Prisma.BotMessageUncheckedCreateWithoutBotInput> | Prisma.BotMessageCreateWithoutBotInput[] | Prisma.BotMessageUncheckedCreateWithoutBotInput[]
  connectOrCreate?: Prisma.BotMessageCreateOrConnectWithoutBotInput | Prisma.BotMessageCreateOrConnectWithoutBotInput[]
  createMany?: Prisma.BotMessageCreateManyBotInputEnvelope
  connect?: Prisma.BotMessageWhereUniqueInput | Prisma.BotMessageWhereUniqueInput[]
}

export type BotMessageUpdateManyWithoutBotNestedInput = {
  create?: Prisma.XOR<Prisma.BotMessageCreateWithoutBotInput, Prisma.BotMessageUncheckedCreateWithoutBotInput> | Prisma.BotMessageCreateWithoutBotInput[] | Prisma.BotMessageUncheckedCreateWithoutBotInput[]
  connectOrCreate?: Prisma.BotMessageCreateOrConnectWithoutBotInput | Prisma.BotMessageCreateOrConnectWithoutBotInput[]
  upsert?: Prisma.BotMessageUpsertWithWhereUniqueWithoutBotInput | Prisma.BotMessageUpsertWithWhereUniqueWithoutBotInput[]
  createMany?: Prisma.BotMessageCreateManyBotInputEnvelope
  set?: Prisma.BotMessageWhereUniqueInput | Prisma.BotMessageWhereUniqueInput[]
  disconnect?: Prisma.BotMessageWhereUniqueInput | Prisma.BotMessageWhereUniqueInput[]
  delete?: Prisma.BotMessageWhereUniqueInput | Prisma.BotMessageWhereUniqueInput[]
  connect?: Prisma.BotMessageWhereUniqueInput | Prisma.BotMessageWhereUniqueInput[]
  update?: Prisma.BotMessageUpdateWithWhereUniqueWithoutBotInput | Prisma.BotMessageUpdateWithWhereUniqueWithoutBotInput[]
  updateMany?: Prisma.BotMessageUpdateManyWithWhereWithoutBotInput | Prisma.BotMessageUpdateManyWithWhereWithoutBotInput[]
  deleteMany?: Prisma.BotMessageScalarWhereInput | Prisma.BotMessageScalarWhereInput[]
}

export type BotMessageUncheckedUpdateManyWithoutBotNestedInput = {
  create?: Prisma.XOR<Prisma.BotMessageCreateWithoutBotInput, Prisma.BotMessageUncheckedCreateWithoutBotInput> | Prisma.BotMessageCreateWithoutBotInput[] | Prisma.BotMessageUncheckedCreateWithoutBotInput[]
  connectOrCreate?: Prisma.BotMessageCreateOrConnectWithoutBotInput | Prisma.BotMessageCreateOrConnectWithoutBotInput[]
  upsert?: Prisma.BotMessageUpsertWithWhereUniqueWithoutBotInput | Prisma.BotMessageUpsertWithWhereUniqueWithoutBotInput[]
  createMany?: Prisma.BotMessageCreateManyBotInputEnvelope
  set?: Prisma.BotMessageWhereUniqueInput | Prisma.BotMessageWhereUniqueInput[]
  disconnect?: Prisma.BotMessageWhereUniqueInput | Prisma.BotMessageWhereUniqueInput[]
  delete?: Prisma.BotMessageWhereUniqueInput | Prisma.BotMessageWhereUniqueInput[]
  connect?: Prisma.BotMessageWhereUniqueInput | Prisma.BotMessageWhereUniqueInput[]
  update?: Prisma.BotMessageUpdateWithWhereUniqueWithoutBotInput | Prisma.BotMessageUpdateWithWhereUniqueWithoutBotInput[]
  updateMany?: Prisma.BotMessageUpdateManyWithWhereWithoutBotInput | Prisma.BotMessageUpdateManyWithWhereWithoutBotInput[]
  deleteMany?: Prisma.BotMessageScalarWhereInput | Prisma.BotMessageScalarWhereInput[]
}

export type EnumBotMessageStatusFieldUpdateOperationsInput = {
  set?: $Enums.BotMessageStatus
}

export type BotMessageCreateWithoutBotInput = {
  id?: string
  channelId: string
  guildId?: string | null
  content: string
  externalMessageId: string
  status?: $Enums.BotMessageStatus
  errorMessage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BotMessageUncheckedCreateWithoutBotInput = {
  id?: string
  channelId: string
  guildId?: string | null
  content: string
  externalMessageId: string
  status?: $Enums.BotMessageStatus
  errorMessage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BotMessageCreateOrConnectWithoutBotInput = {
  where: Prisma.BotMessageWhereUniqueInput
  create: Prisma.XOR<Prisma.BotMessageCreateWithoutBotInput, Prisma.BotMessageUncheckedCreateWithoutBotInput>
}

export type BotMessageCreateManyBotInputEnvelope = {
  data: Prisma.BotMessageCreateManyBotInput | Prisma.BotMessageCreateManyBotInput[]
  skipDuplicates?: boolean
}

export type BotMessageUpsertWithWhereUniqueWithoutBotInput = {
  where: Prisma.BotMessageWhereUniqueInput
  update: Prisma.XOR<Prisma.BotMessageUpdateWithoutBotInput, Prisma.BotMessageUncheckedUpdateWithoutBotInput>
  create: Prisma.XOR<Prisma.BotMessageCreateWithoutBotInput, Prisma.BotMessageUncheckedCreateWithoutBotInput>
}

export type BotMessageUpdateWithWhereUniqueWithoutBotInput = {
  where: Prisma.BotMessageWhereUniqueInput
  data: Prisma.XOR<Prisma.BotMessageUpdateWithoutBotInput, Prisma.BotMessageUncheckedUpdateWithoutBotInput>
}

export type BotMessageUpdateManyWithWhereWithoutBotInput = {
  where: Prisma.BotMessageScalarWhereInput
  data: Prisma.XOR<Prisma.BotMessageUpdateManyMutationInput, Prisma.BotMessageUncheckedUpdateManyWithoutBotInput>
}

export type BotMessageScalarWhereInput = {
  AND?: Prisma.BotMessageScalarWhereInput | Prisma.BotMessageScalarWhereInput[]
  OR?: Prisma.BotMessageScalarWhereInput[]
  NOT?: Prisma.BotMessageScalarWhereInput | Prisma.BotMessageScalarWhereInput[]
  id?: Prisma.StringFilter<"BotMessage"> | string
  botId?: Prisma.StringFilter<"BotMessage"> | string
  channelId?: Prisma.StringFilter<"BotMessage"> | string
  guildId?: Prisma.StringNullableFilter<"BotMessage"> | string | null
  content?: Prisma.StringFilter<"BotMessage"> | string
  externalMessageId?: Prisma.StringFilter<"BotMessage"> | string
  status?: Prisma.EnumBotMessageStatusFilter<"BotMessage"> | $Enums.BotMessageStatus
  errorMessage?: Prisma.StringNullableFilter<"BotMessage"> | string | null
  createdAt?: Prisma.DateTimeFilter<"BotMessage"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BotMessage"> | Date | string
}

export type BotMessageCreateManyBotInput = {
  id?: string
  channelId: string
  guildId?: string | null
  content: string
  externalMessageId: string
  status?: $Enums.BotMessageStatus
  errorMessage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BotMessageUpdateWithoutBotInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.StringFieldUpdateOperationsInput | string
  externalMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBotMessageStatusFieldUpdateOperationsInput | $Enums.BotMessageStatus
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BotMessageUncheckedUpdateWithoutBotInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.StringFieldUpdateOperationsInput | string
  externalMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBotMessageStatusFieldUpdateOperationsInput | $Enums.BotMessageStatus
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BotMessageUncheckedUpdateManyWithoutBotInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.StringFieldUpdateOperationsInput | string
  externalMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBotMessageStatusFieldUpdateOperationsInput | $Enums.BotMessageStatus
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type BotMessageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  botId?: boolean
  channelId?: boolean
  guildId?: boolean
  content?: boolean
  externalMessageId?: boolean
  status?: boolean
  errorMessage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  bot?: boolean | Prisma.BotDefaultArgs<ExtArgs>
}, ExtArgs["result"]["botMessage"]>

export type BotMessageSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  botId?: boolean
  channelId?: boolean
  guildId?: boolean
  content?: boolean
  externalMessageId?: boolean
  status?: boolean
  errorMessage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  bot?: boolean | Prisma.BotDefaultArgs<ExtArgs>
}, ExtArgs["result"]["botMessage"]>

export type BotMessageSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  botId?: boolean
  channelId?: boolean
  guildId?: boolean
  content?: boolean
  externalMessageId?: boolean
  status?: boolean
  errorMessage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  bot?: boolean | Prisma.BotDefaultArgs<ExtArgs>
}, ExtArgs["result"]["botMessage"]>

export type BotMessageSelectScalar = {
  id?: boolean
  botId?: boolean
  channelId?: boolean
  guildId?: boolean
  content?: boolean
  externalMessageId?: boolean
  status?: boolean
  errorMessage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type BotMessageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "botId" | "channelId" | "guildId" | "content" | "externalMessageId" | "status" | "errorMessage" | "createdAt" | "updatedAt", ExtArgs["result"]["botMessage"]>
export type BotMessageInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bot?: boolean | Prisma.BotDefaultArgs<ExtArgs>
}
export type BotMessageIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bot?: boolean | Prisma.BotDefaultArgs<ExtArgs>
}
export type BotMessageIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bot?: boolean | Prisma.BotDefaultArgs<ExtArgs>
}

export type $BotMessagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BotMessage"
  objects: {
    bot: Prisma.$BotPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    botId: string
    channelId: string
    guildId: string | null
    content: string
    externalMessageId: string
    status: $Enums.BotMessageStatus
    errorMessage: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["botMessage"]>
  composites: {}
}

export type BotMessageGetPayload<S extends boolean | null | undefined | BotMessageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BotMessagePayload, S>

export type BotMessageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BotMessageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BotMessageCountAggregateInputType | true
  }

export interface BotMessageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BotMessage'], meta: { name: 'BotMessage' } }
  /**
   * Find zero or one BotMessage that matches the filter.
   * @param {BotMessageFindUniqueArgs} args - Arguments to find a BotMessage
   * @example
   * // Get one BotMessage
   * const botMessage = await prisma.botMessage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BotMessageFindUniqueArgs>(args: Prisma.SelectSubset<T, BotMessageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BotMessageClient<runtime.Types.Result.GetResult<Prisma.$BotMessagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BotMessage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BotMessageFindUniqueOrThrowArgs} args - Arguments to find a BotMessage
   * @example
   * // Get one BotMessage
   * const botMessage = await prisma.botMessage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BotMessageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BotMessageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BotMessageClient<runtime.Types.Result.GetResult<Prisma.$BotMessagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BotMessage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BotMessageFindFirstArgs} args - Arguments to find a BotMessage
   * @example
   * // Get one BotMessage
   * const botMessage = await prisma.botMessage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BotMessageFindFirstArgs>(args?: Prisma.SelectSubset<T, BotMessageFindFirstArgs<ExtArgs>>): Prisma.Prisma__BotMessageClient<runtime.Types.Result.GetResult<Prisma.$BotMessagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BotMessage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BotMessageFindFirstOrThrowArgs} args - Arguments to find a BotMessage
   * @example
   * // Get one BotMessage
   * const botMessage = await prisma.botMessage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BotMessageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BotMessageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BotMessageClient<runtime.Types.Result.GetResult<Prisma.$BotMessagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BotMessages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BotMessageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BotMessages
   * const botMessages = await prisma.botMessage.findMany()
   * 
   * // Get first 10 BotMessages
   * const botMessages = await prisma.botMessage.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const botMessageWithIdOnly = await prisma.botMessage.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BotMessageFindManyArgs>(args?: Prisma.SelectSubset<T, BotMessageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BotMessagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BotMessage.
   * @param {BotMessageCreateArgs} args - Arguments to create a BotMessage.
   * @example
   * // Create one BotMessage
   * const BotMessage = await prisma.botMessage.create({
   *   data: {
   *     // ... data to create a BotMessage
   *   }
   * })
   * 
   */
  create<T extends BotMessageCreateArgs>(args: Prisma.SelectSubset<T, BotMessageCreateArgs<ExtArgs>>): Prisma.Prisma__BotMessageClient<runtime.Types.Result.GetResult<Prisma.$BotMessagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BotMessages.
   * @param {BotMessageCreateManyArgs} args - Arguments to create many BotMessages.
   * @example
   * // Create many BotMessages
   * const botMessage = await prisma.botMessage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BotMessageCreateManyArgs>(args?: Prisma.SelectSubset<T, BotMessageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BotMessages and returns the data saved in the database.
   * @param {BotMessageCreateManyAndReturnArgs} args - Arguments to create many BotMessages.
   * @example
   * // Create many BotMessages
   * const botMessage = await prisma.botMessage.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BotMessages and only return the `id`
   * const botMessageWithIdOnly = await prisma.botMessage.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BotMessageCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BotMessageCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BotMessagePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BotMessage.
   * @param {BotMessageDeleteArgs} args - Arguments to delete one BotMessage.
   * @example
   * // Delete one BotMessage
   * const BotMessage = await prisma.botMessage.delete({
   *   where: {
   *     // ... filter to delete one BotMessage
   *   }
   * })
   * 
   */
  delete<T extends BotMessageDeleteArgs>(args: Prisma.SelectSubset<T, BotMessageDeleteArgs<ExtArgs>>): Prisma.Prisma__BotMessageClient<runtime.Types.Result.GetResult<Prisma.$BotMessagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BotMessage.
   * @param {BotMessageUpdateArgs} args - Arguments to update one BotMessage.
   * @example
   * // Update one BotMessage
   * const botMessage = await prisma.botMessage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BotMessageUpdateArgs>(args: Prisma.SelectSubset<T, BotMessageUpdateArgs<ExtArgs>>): Prisma.Prisma__BotMessageClient<runtime.Types.Result.GetResult<Prisma.$BotMessagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BotMessages.
   * @param {BotMessageDeleteManyArgs} args - Arguments to filter BotMessages to delete.
   * @example
   * // Delete a few BotMessages
   * const { count } = await prisma.botMessage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BotMessageDeleteManyArgs>(args?: Prisma.SelectSubset<T, BotMessageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BotMessages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BotMessageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BotMessages
   * const botMessage = await prisma.botMessage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BotMessageUpdateManyArgs>(args: Prisma.SelectSubset<T, BotMessageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BotMessages and returns the data updated in the database.
   * @param {BotMessageUpdateManyAndReturnArgs} args - Arguments to update many BotMessages.
   * @example
   * // Update many BotMessages
   * const botMessage = await prisma.botMessage.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BotMessages and only return the `id`
   * const botMessageWithIdOnly = await prisma.botMessage.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BotMessageUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BotMessageUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BotMessagePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BotMessage.
   * @param {BotMessageUpsertArgs} args - Arguments to update or create a BotMessage.
   * @example
   * // Update or create a BotMessage
   * const botMessage = await prisma.botMessage.upsert({
   *   create: {
   *     // ... data to create a BotMessage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BotMessage we want to update
   *   }
   * })
   */
  upsert<T extends BotMessageUpsertArgs>(args: Prisma.SelectSubset<T, BotMessageUpsertArgs<ExtArgs>>): Prisma.Prisma__BotMessageClient<runtime.Types.Result.GetResult<Prisma.$BotMessagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BotMessages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BotMessageCountArgs} args - Arguments to filter BotMessages to count.
   * @example
   * // Count the number of BotMessages
   * const count = await prisma.botMessage.count({
   *   where: {
   *     // ... the filter for the BotMessages we want to count
   *   }
   * })
  **/
  count<T extends BotMessageCountArgs>(
    args?: Prisma.Subset<T, BotMessageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BotMessageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BotMessage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BotMessageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BotMessageAggregateArgs>(args: Prisma.Subset<T, BotMessageAggregateArgs>): Prisma.PrismaPromise<GetBotMessageAggregateType<T>>

  /**
   * Group by BotMessage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BotMessageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BotMessageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BotMessageGroupByArgs['orderBy'] }
      : { orderBy?: BotMessageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BotMessageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBotMessageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BotMessage model
 */
readonly fields: BotMessageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BotMessage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BotMessageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  bot<T extends Prisma.BotDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BotDefaultArgs<ExtArgs>>): Prisma.Prisma__BotClient<runtime.Types.Result.GetResult<Prisma.$BotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BotMessage model
 */
export interface BotMessageFieldRefs {
  readonly id: Prisma.FieldRef<"BotMessage", 'String'>
  readonly botId: Prisma.FieldRef<"BotMessage", 'String'>
  readonly channelId: Prisma.FieldRef<"BotMessage", 'String'>
  readonly guildId: Prisma.FieldRef<"BotMessage", 'String'>
  readonly content: Prisma.FieldRef<"BotMessage", 'String'>
  readonly externalMessageId: Prisma.FieldRef<"BotMessage", 'String'>
  readonly status: Prisma.FieldRef<"BotMessage", 'BotMessageStatus'>
  readonly errorMessage: Prisma.FieldRef<"BotMessage", 'String'>
  readonly createdAt: Prisma.FieldRef<"BotMessage", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"BotMessage", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BotMessage findUnique
 */
export type BotMessageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotMessage
   */
  select?: Prisma.BotMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotMessage
   */
  omit?: Prisma.BotMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotMessageInclude<ExtArgs> | null
  /**
   * Filter, which BotMessage to fetch.
   */
  where: Prisma.BotMessageWhereUniqueInput
}

/**
 * BotMessage findUniqueOrThrow
 */
export type BotMessageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotMessage
   */
  select?: Prisma.BotMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotMessage
   */
  omit?: Prisma.BotMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotMessageInclude<ExtArgs> | null
  /**
   * Filter, which BotMessage to fetch.
   */
  where: Prisma.BotMessageWhereUniqueInput
}

/**
 * BotMessage findFirst
 */
export type BotMessageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotMessage
   */
  select?: Prisma.BotMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotMessage
   */
  omit?: Prisma.BotMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotMessageInclude<ExtArgs> | null
  /**
   * Filter, which BotMessage to fetch.
   */
  where?: Prisma.BotMessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BotMessages to fetch.
   */
  orderBy?: Prisma.BotMessageOrderByWithRelationInput | Prisma.BotMessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BotMessages.
   */
  cursor?: Prisma.BotMessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BotMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BotMessages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BotMessages.
   */
  distinct?: Prisma.BotMessageScalarFieldEnum | Prisma.BotMessageScalarFieldEnum[]
}

/**
 * BotMessage findFirstOrThrow
 */
export type BotMessageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotMessage
   */
  select?: Prisma.BotMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotMessage
   */
  omit?: Prisma.BotMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotMessageInclude<ExtArgs> | null
  /**
   * Filter, which BotMessage to fetch.
   */
  where?: Prisma.BotMessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BotMessages to fetch.
   */
  orderBy?: Prisma.BotMessageOrderByWithRelationInput | Prisma.BotMessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BotMessages.
   */
  cursor?: Prisma.BotMessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BotMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BotMessages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BotMessages.
   */
  distinct?: Prisma.BotMessageScalarFieldEnum | Prisma.BotMessageScalarFieldEnum[]
}

/**
 * BotMessage findMany
 */
export type BotMessageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotMessage
   */
  select?: Prisma.BotMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotMessage
   */
  omit?: Prisma.BotMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotMessageInclude<ExtArgs> | null
  /**
   * Filter, which BotMessages to fetch.
   */
  where?: Prisma.BotMessageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BotMessages to fetch.
   */
  orderBy?: Prisma.BotMessageOrderByWithRelationInput | Prisma.BotMessageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BotMessages.
   */
  cursor?: Prisma.BotMessageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BotMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BotMessages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BotMessages.
   */
  distinct?: Prisma.BotMessageScalarFieldEnum | Prisma.BotMessageScalarFieldEnum[]
}

/**
 * BotMessage create
 */
export type BotMessageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotMessage
   */
  select?: Prisma.BotMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotMessage
   */
  omit?: Prisma.BotMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotMessageInclude<ExtArgs> | null
  /**
   * The data needed to create a BotMessage.
   */
  data: Prisma.XOR<Prisma.BotMessageCreateInput, Prisma.BotMessageUncheckedCreateInput>
}

/**
 * BotMessage createMany
 */
export type BotMessageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BotMessages.
   */
  data: Prisma.BotMessageCreateManyInput | Prisma.BotMessageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BotMessage createManyAndReturn
 */
export type BotMessageCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotMessage
   */
  select?: Prisma.BotMessageSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BotMessage
   */
  omit?: Prisma.BotMessageOmit<ExtArgs> | null
  /**
   * The data used to create many BotMessages.
   */
  data: Prisma.BotMessageCreateManyInput | Prisma.BotMessageCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotMessageIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BotMessage update
 */
export type BotMessageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotMessage
   */
  select?: Prisma.BotMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotMessage
   */
  omit?: Prisma.BotMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotMessageInclude<ExtArgs> | null
  /**
   * The data needed to update a BotMessage.
   */
  data: Prisma.XOR<Prisma.BotMessageUpdateInput, Prisma.BotMessageUncheckedUpdateInput>
  /**
   * Choose, which BotMessage to update.
   */
  where: Prisma.BotMessageWhereUniqueInput
}

/**
 * BotMessage updateMany
 */
export type BotMessageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BotMessages.
   */
  data: Prisma.XOR<Prisma.BotMessageUpdateManyMutationInput, Prisma.BotMessageUncheckedUpdateManyInput>
  /**
   * Filter which BotMessages to update
   */
  where?: Prisma.BotMessageWhereInput
  /**
   * Limit how many BotMessages to update.
   */
  limit?: number
}

/**
 * BotMessage updateManyAndReturn
 */
export type BotMessageUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotMessage
   */
  select?: Prisma.BotMessageSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BotMessage
   */
  omit?: Prisma.BotMessageOmit<ExtArgs> | null
  /**
   * The data used to update BotMessages.
   */
  data: Prisma.XOR<Prisma.BotMessageUpdateManyMutationInput, Prisma.BotMessageUncheckedUpdateManyInput>
  /**
   * Filter which BotMessages to update
   */
  where?: Prisma.BotMessageWhereInput
  /**
   * Limit how many BotMessages to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotMessageIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BotMessage upsert
 */
export type BotMessageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotMessage
   */
  select?: Prisma.BotMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotMessage
   */
  omit?: Prisma.BotMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotMessageInclude<ExtArgs> | null
  /**
   * The filter to search for the BotMessage to update in case it exists.
   */
  where: Prisma.BotMessageWhereUniqueInput
  /**
   * In case the BotMessage found by the `where` argument doesn't exist, create a new BotMessage with this data.
   */
  create: Prisma.XOR<Prisma.BotMessageCreateInput, Prisma.BotMessageUncheckedCreateInput>
  /**
   * In case the BotMessage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BotMessageUpdateInput, Prisma.BotMessageUncheckedUpdateInput>
}

/**
 * BotMessage delete
 */
export type BotMessageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotMessage
   */
  select?: Prisma.BotMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotMessage
   */
  omit?: Prisma.BotMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotMessageInclude<ExtArgs> | null
  /**
   * Filter which BotMessage to delete.
   */
  where: Prisma.BotMessageWhereUniqueInput
}

/**
 * BotMessage deleteMany
 */
export type BotMessageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BotMessages to delete
   */
  where?: Prisma.BotMessageWhereInput
  /**
   * Limit how many BotMessages to delete.
   */
  limit?: number
}

/**
 * BotMessage without action
 */
export type BotMessageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotMessage
   */
  select?: Prisma.BotMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotMessage
   */
  omit?: Prisma.BotMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotMessageInclude<ExtArgs> | null
}
